const ESFJ = `
<p><strong>For people with the ESFJ personality type (Consuls)</strong>, life is sweetest when it’s shared with others. These social individuals form the bedrock of many communities, opening their homes – and their hearts – to friends, loved ones, and neighbors.</p>
<h2>ESFJ Strengths</h2>
<p><strong>Strong Practical Skills</strong> – People with the ESFJ personality type (Consuls) are excellent managers of day-to-day tasks and routine maintenance, enjoying making sure that those who are close to them are well cared for.</p>
<p><strong>Strong Sense of Duty</strong> – ESFJs have a strong sense of responsibility and always strive to meet their obligations. This often makes them hardworking and efficient in the workplace and very loyal in their personal relationships. They also tend to uphold the traditions that they hold close to their heart with diligence and consistency.</p>
<p><strong>Very Loyal</strong> – Valuing stability and security very highly, ESFJs are eager to preserve the status quo, which makes them extremely loyal and trustworthy partners and employees. True pillars of any groups that they belong to – whether it is their family or a community club – people with this personality type can always be counted on to show up and lend a helping hand.</p>
<p><strong>Sensitive and Warm</strong> – ESFJs naturally offer others the security and stability that they themselves want and need. They tend to seek out harmony and care deeply about other people’s feelings, being careful not to offend or hurt others. They are strong team players, and win-win situations are the stuff that their smiles are made of.</p>
<p><strong>Good at Connecting with Others</strong> – These qualities come together to make ESFJ personalities social, confident, and generally well-liked. They have a strong need to “belong” and have no problem with small talk or following social cues in order to help them take an active role in their communities.</p>
<h2>ESFJ Weaknesses</h2>
<p><strong>Worried about Their Social Status</strong> – ESFJs can become preoccupied with social status and influence, which affects many of the decisions that they make, potentially limiting their creativity and open-mindedness. They can tie too much of their identity to others’ expectations, losing a sense of themselves.</p>
<p><strong>Inflexible</strong> – ESFJ personalities place a lot of importance on what is socially acceptable and can be very cautious, even critical, of anything unconventional or outside the mainstream. They may also be unwilling to step out of their own comfort zone, usually for fear of being (or just appearing) different.</p>
<p><strong>Vulnerable to Criticism</strong> – It can be especially challenging to change these tendencies because they are so conflict averse. ESFJ personalities can become very defensive and hurt if someone, especially a person close to them, criticizes their habits, beliefs, or traditions.</p>
<p><strong>Often Too Needy</strong> – ESFJs need to hear and see a great deal of appreciation. If their efforts go unnoticed, these individuals may start fishing for compliments in an attempt to get reassurance of how much they are valued.</p>
<p><strong>Too Selfless</strong> – The other side of this is that ESFJ personalities sometimes try to establish their value with doting attention, something that can quickly overwhelm those who don’t need it, making it ultimately unwelcome. Furthermore, they often neglect their own needs in the process.</p>
`;
export default ESFJ;