const ESFP = `
<p><strong>If anyone is to be found spontaneously breaking into song and dance, it is people with the ESFP personality type (Entertainers).</strong> They get caught up in the excitement of the moment and want everyone else to feel that way too. No other type is as generous with their time and energy when it comes to encouraging others, and no other type does it with such irresistible style.</p>
<h2>ESFP Strengths</h2>
<p><strong>Bold</strong> – People with the ESFP personality type (Entertainers) aren’t known for holding back. Wanting to experience everything there is to experience, they don’t mind stepping out of their comfort zones when no one else is willing.</p>
<p><strong>Original</strong> – Traditions and expectations are secondary to this personality type, if a consideration at all. ESFPs love to experiment with new styles and constantly find new ways to stand out in the crowd. Not stopping at mere outfits, they inject stylistic creativity into their words and actions too. Every day is a performance, and they love to put on a show.</p>
<p><strong>Positive and Enthusiastic</strong> – ESFPs are known for their zest for life and infectious enthusiasm. They naturally exude the kind of positivity that lights up a room and draws people to them, and this often translates into an engaging charisma that can inspire those around them. They tend to approach life and its multitude of experiences with an open mind, ready to immerse themselves in the new, the delightful, and the unexpected.</p>
<p><strong>Hands-on and Observant</strong> – To ESFPs, the world is meant to be felt and experienced. They prefer to see and do than to wax philosophical about “what-ifs.” With all this focus on the here and now, on doing and acting, it makes sense that ESFP personalities are naturals when it comes to noticing real, tangible things and changes.</p>
<p><strong>Excellent People Skills</strong> – More so than things, though, ESFPs love to pay attention to people. They are talkative, witty, and almost never run out of things to discuss. For these personalities, happiness and satisfaction stem from the time they spend with the people they enjoy being with.</p>
<h2>ESFP Weaknesses</h2>
<p><strong>Sensitive</strong> – ESFPs are strongly emotional and often vulnerable to criticism – they can feel like they’ve been backed into a corner, sometimes reacting badly. This is probably their greatest weakness, because it makes it so hard to address any other weaknesses brought to light.</p>
<p><strong>Conflict-Averse</strong> – ESFP personalities sometimes ignore and avoid conflict entirely. They tend to say and do what’s needed to get out of such situations, then move on to something more fun.</p>
<p><strong>Easily Bored</strong> – Without constant excitement, people with this personality type often find ways to create it themselves. Risky behavior, self-indulgence, and the pleasures of the moment over long-term plans are all things that ESFPs get into a little too often.</p>
<p><strong>Poor Long-Term Planners</strong> – ESFP personalities rarely make detailed plans for the future. To them, things come as they come, and too often they don’t bother with taking the time to lay out steps and consequences, believing that they could change at any moment.</p>
<p><strong>Unfocused</strong> – Anything that requires long-term dedication and focus is a particular challenge for people with the ESFP personality type. In academics, dense, unchanging subjects are much more difficult than more dynamic, relatable subjects. The trick for them is to find day-to-day joy in broader goals and to tough it out with those tedious things that must be done.</p>
`;
export default ESFP;