const ESTJ = `
<p><strong>People with the ESTJ personality type (Executives)</strong> are representatives of tradition and order, utilizing their understanding of what is right, wrong, and socially acceptable to bring families and communities together. Embracing the values of honesty and dedication, ESTJs are valued for their mentorship mindset and their ability to create and follow through on plans in a diligent and efficient manner. They will happily lead the way on difficult paths, and they won’t give up when things become stressful.</p>
<h2>ESTJ Strengths</h2>
<p><strong>Dedicated</strong> – Seeing things to completion borders on an ethical obligation for people with the ESTJ personality type (Executives). Tasks aren’t simply abandoned because they’ve become difficult or boring. They showcase their dedication through their unwavering commitment to high standards. In fact, they tend to strive for perfection in most things that they take on in life.</p>
<p><strong>Strong-willed</strong> – A strong will makes this dedication possible, and ESTJs don’t give up their beliefs because of simple opposition. They defend their ideas and principles relentlessly and must be proven clearly and conclusively wrong for their stance to budge.</p>
<p><strong>Direct and Honest</strong> – ESTJs trust facts far more than abstract ideas or opinions. Straightforward statements and information are king, and people with this personality type return the honesty (whether it’s wanted or not).</p>
<p><strong>Loyal, Patient, and Reliable</strong> – ESTJs work to exemplify truthfulness and reliability, considering stability and security very important. When ESTJs say they’ll do something, they keep their word, making them very responsible members of their families, companies, and communities.</p>
<p><strong>Enjoy Creating Order</strong> – Chaos makes things unpredictable, and unpredictable things can’t be trusted when they are needed most. With this in mind, ESTJs strive to create order and security in their environments by establishing rules, structures, and clear roles. They tend to exemplify this need for order in their home lives as well, as they are the most likely personality type to have a very structured schedule that includes fixed times for waking up and going to sleep.</p>
<p><strong>Excellent Organizers</strong> – A commitment to truth and clear standards makes ESTJs capable and confident leaders. People with this personality type have no problem distributing tasks and responsibilities to others fairly and objectively, making them excellent administrators.</p>
<h2>ESTJ Weaknesses</h2>
<p><strong>Inflexible and Stubborn</strong> – The problem with being so fixated on what works is that they too often dismiss what might work better. Everything is opinion until proven, and ESTJ personalities are reluctant to trust an opinion long enough for it to have that chance.</p>
<p><strong>Uncomfortable with Change</strong> – ESTJs are strong adherents to tradition. When suddenly forced to try unvetted solutions, they become uncomfortable and stressed. New ideas suggest that their methods weren’t good enough, and abandoning what has always worked before in favor of something that may yet fail risks their image of reliability.</p>
<p><strong>Judgmental</strong> – People with the ESTJ personality type have strong convictions about what is right, wrong, and socially acceptable, and their compulsion to create order often extends to all things and everyone, ignoring the possibility that there is more than one right way to get things done. They do not hesitate to let people they disagree with know what they think, considering it their duty to set things right.</p>
<p><strong>Too Focused on Social Status</strong> – ESTJs take pride in the respect of their friends, colleagues, and community, and while difficult to admit, they are very concerned with public opinion. These personalities can get caught up in meeting others’ expectations, failing to address their own needs.</p>
<p><strong>Difficulty Relaxing</strong> – This need for respect fosters a need to maintain their dignity, which can make it difficult for ESTJs to cut loose and relax for risk of dropping the ball or looking the fool, even in good fun.</p>
`;
export default ESTJ;