const ESTP = `
<p><strong>People with the ESTP personality type (Entrepreneurs)</strong> are vibrant individuals brimming with an enthusiastic and spontaneous energy. They tend to be on the competitive side, often assuming that a competitive mindset is a necessity in order to achieve success in life. With their driven, action-oriented attitudes, they rarely waste time thinking about the past. In fact, they excel at keeping their attention rooted in their present – so much so that they rarely find themselves fixated on the time throughout the day.</p>
<h2>ESTP Strengths</h2>
<p><strong>Bold</strong> – People with the ESTP personality type (Entrepreneurs) are full of life and energy. There is no greater joy for them than pushing boundaries and discovering and applying new tools and ideas.</p>
<p><strong>Rational and Practical</strong> – These personalities love knowledge and philosophy, but not for their own sake. What’s fun for ESTPs is finding ideas that are actionable and drilling into the details so they can put them to use. If a discussion is completely arbitrary, there are better uses for their time.</p>
<p><strong>Original</strong> – Combining their boldness and practicality, ESTP personalities love to experiment with new ideas and solutions. They put things together in ways that no one else would think to.</p>
<p><strong>Perceptive</strong> – Their originality is helped by their ability to notice when things change – and when they need to change! Small shifts in habits and appearances stick out to ESTPs, and they use these observations to help create connections with others.</p>
<p><strong>Direct</strong> – ESTPs’ perceptiveness isn’t used for mind games – they prefer to communicate clearly, with direct and factual questions and answers. What you see is what you get with this personality type.</p>
<p><strong>Sociable</strong> – All these qualities pull together to make ESTP personalities natural group leaders. This isn’t something that they actively seek – they just have a knack for making excellent use of social interactions and networking opportunities.</p>
<h2>ESTP Weaknesses</h2>
<p><strong>Insensitive</strong> – Feelings and emotions come second to facts and pragmatism for people with the ESTP personality type. Emotionally charged situations are awkward, uncomfortable affairs, and blunt honesty doesn’t help here. They often have a lot of trouble acknowledging and expressing their own feelings as well, preferring not to dwell on heavy topics or the past for too long.</p>
<p><strong>Impatient</strong> – ESTPs move at their own pace to keep themselves entertained. Slowing down because someone else “doesn’t get it” or having to stay focused on a single detail for too long is extremely challenging for them.</p>
<p><strong>Impulsive</strong> – Impatience can lead ESTPs to push into uncharted territory without thinking of the long-term consequences. These personalities sometimes intentionally combat boredom with extra risk.</p>
<p><strong>Unstructured</strong> – ESTPs see an opportunity – to fix a problem, to advance, to have fun – and seize the moment, often ignoring rules and social expectations in the process. This can result in them getting things done, but it can also create unexpected social fallout if it rubs more traditional personality types the wrong way.</p>
<p><strong>May Miss the Bigger Picture</strong> – Living in the moment can cause ESTPs to miss the forest for the trees. People with this personality type love to solve problems here and now – perhaps too much. All parts of a project can be perfect, but the project will still fail if those parts do not fit together.</p>
<p><strong>Defiant</strong> – This type won’t be boxed in. Repetition, hardline rules, and sitting quietly while being lectured at are things that ESTP personalities don’t normally enjoy. They are action oriented and hands-on. Environments like school and much entry-level work can be so tedious that they’re intolerable, requiring extraordinary effort from ESTPs to stay focused long enough to get to freer positions.</p>
`;
export default ESTP;