const INFP = `<p><strong>Although they may seem quiet or unassuming, people with the INFP personality type (Mediators)</strong> have vibrant, passionate inner lives. Creative and imaginative, they happily lose themselves in daydreams, inventing all sorts of stories and conversations in their mind. INFPs are known for their sensitivity – these personalities can have profound emotional responses to music, art, nature, and the people around them. They are known to be extremely sentimental and nostalgic, often holding onto special keepsakes and memorabilia that brighten their days and fill their heart with joy.</p>
        <h2>INFP Strengths</h2>
        <p><strong>Empathetic</strong> – People with the INFP personality type (Mediators) don’t just care about those around them in an abstract sense – they can actually feel another person’s emotions, from joy and elation to sorrow and regret. Because of their sensitivity, these personalities tend to be thoughtful and kindhearted, and they hate the idea of hurting anyone, even unintentionally.</p>
    
        <p><strong>Generous</strong> – INFPs rarely enjoy succeeding at others’ expense. They feel called to share the good things in their lives, give credit where it’s due, and uplift the people around them. These personalities want to contribute to a world where every voice is heard and no one’s needs go unmet.</p>
    
        <p><strong>Open-Minded</strong> – Tolerant and accepting, INFPs try not to judge anyone else’s beliefs, lifestyles, or decisions. This is a personality type that prefers compassion to faultfinding. Many feel empathy even for those who have done wrong. Because they’re so accepting, INFPs often become confidants for their friends and loved ones – and occasionally for total strangers.</p>
    
        <p><strong>Creative</strong> – INFP personalities love to see things from unconventional perspectives. Few things give them more pleasure than allowing their mind to wander through all sorts of ideas and possibilities and daydreams. It’s no wonder, then, that many INFPs are drawn to creative pursuits – or that this personality type is well represented among writers and artists.</p>
    
        <p><strong>Passionate</strong> – INFPs contain a deep well of passion, primarily driven by their profound empathy, strong internal values, and ceaseless curiosity about the human experience. When an idea or movement captures their imagination, these individuals want to give their whole heart to it. People with the INFP personality type may not always be outspoken, but that doesn’t diminish their strong feelings for a cause that speaks to their beliefs and convictions.</p>
    
        <p><strong>Idealistic</strong> – INFP personalities strive to follow their conscience even when doing the right thing isn’t easy or convenient. They rarely lose sight of their desire to live a meaningful, purpose-filled life – one that helps others and leaves the world a better place.</p>
    
        <h2>INFP Weaknesses</h2>
        <p><strong>Unrealistic</strong> – Nothing in this world is perfect – and that can be a difficult truth for INFPs to accept. People with this personality type can be hopeless romantics, with rose-colored visions of what their lives should be like. This can set them up for disappointment when reality inevitably falls short of their dreams.</p>
    
        <p><strong>Self-Isolating</strong> – INFP personalities long to connect with others, but they don’t always know how. Especially in new environments, they may be reluctant to put themselves out there in ways that would help them make new friends or become involved in a new community. As a result, people with the INFP personality type may sometimes feel lonely or isolated.</p>
    
        <p><strong>Unfocused</strong> – INFPs’ imaginative, introspective nature doesn’t always lend itself to productivity. Many people with this personality type get frustrated by how difficult they find it to buckle down and get things done. The problem isn’t that they are incapable – rather, it’s that INFPs run into problems when they become so caught up in different ideas and ideals that they fail to commit to a course of action.</p>

        <p><strong>Emotionally Vulnerable</strong> – The emotional attunement of these personalities is among their greatest strengths. But unless they establish boundaries, they can be at risk of absorbing other people’s negative moods or attitudes. And this can be detrimental to their personal peace and productivity, as INFPs are the most likely personality type to say negative emotions get in the way of their ability to think clearly.</p>
    
        <p><strong>Too Eager to Please</strong> – Conflict tends to be stressful for INFPs, who yearn for harmony and acceptance. When someone dislikes or disapproves of them, these personalities may become fixated on trying to clear the air and change that person’s mind. They might even take responsibility and apologize for things that are not their fault at all in an effort to make sure that they are in everyone’s good graces. Unfortunately, INFPs’ desire to please others can drain their energy, eclipsing their inner wisdom and their awareness of their own needs.</p>
    
        <p><strong>Self-Critical</strong> – INFPs believe in their unique potential, and they desperately want to live up to it. But this can cause them to have unrealistic expectations for themselves. When these personalities fail to live up to these visions, they may accuse themselves of being useless or selfish or woefully inadequate. Taken too far, this self-criticism can discourage INFPs, leading them to give up on even their dearest dreams.</p>`;
export default INFP;